---
title: "motif_scraper_figures"
author: "E. Roberson"
date: "February 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message=FALSE,
	fig.path="figures/",
	fig.keep='all',
	dpi=150,
	fig.width=11,
	fig.height=8.5,
	fig.ext='jpeg' )
```

# Import and setup

```{r imports}
library( tidyverse )
library( stringr )
library( cowplot )
library( UpSetR )
```

```{r fxn}
read_times <- function( filename, skip_num=15 ) {
	read_delim( filename, delim = "\t", col_names = FALSE, col_types = 'c', skip = skip_num ) %>%
		as.data.frame( . ) %>%
		unlist( . ) %>%
		unname( . ) %>%
		strsplit( " " ) %>%
		unlist( . ) %>%
		.[ 1 ] %>%
		as.numeric( . ) %>%
		return( . )
}
```

# Read benchmarks and plot outcomes

```{r read_data}
file_path = "benchmark"

runtimes <- data_frame( filename = dir( file_path, pattern="*.log" ) ) %>%
	mutate( full_path = file.path( file_path, filename ) ) %>%
	mutate( actual_time = map( full_path, read_times ) ) %>%
	unnest( . ) %>%
	mutate( tosplit = str_replace( filename, ".log", "" ) ) %>%
	separate( col = tosplit, into = c( "CPU", "Iteration", "Motif" ), sep = "_" )
```

```{r summary_stats}
run_stats <- runtimes %>%
	group_by( Motif, CPU ) %>%
	summarize( mean_time = mean( actual_time ), sd_time = sd( actual_time ) )
```

```{r run_time_separate}
ctcf.plot <- run_stats %>%
	filter( Motif == "NNNMCDSNAGRDGDHRVNN" ) %>%
	ggplot( ., aes( x = as.numeric( CPU ), y = mean_time ) ) +
	geom_ribbon( aes( ymin = mean_time - sd_time, ymax = mean_time + sd_time ), fill="#999999" ) +
	geom_line() +
	ggtitle( "CTCF" ) +
	scale_x_continuous( breaks=seq( 1, 10 ) ) +
	xlab( "\nProcessors" ) +
	ylab( "Time (s)\n" ) +
	theme_bw() +
	theme(
		axis.title = element_text( size=22 ),
		axis.text = element_text( size=20 ),
		plot.title = element_text( size=22, hjust=0.5 )
	)
	
cebpb.plot <- run_stats %>%
	filter( Motif == "VTKDYRHAAY" ) %>%
	ggplot( ., aes( x = as.numeric( CPU ), y = mean_time ) ) +
	geom_ribbon( aes( ymin = mean_time - sd_time, ymax = mean_time + sd_time ), fill="#999999" ) +
	geom_line() +
	scale_x_continuous( breaks=seq( 1, 10 ) ) +
	xlab( "\nProcessors" ) +
	ylab( "Time (s)\n" ) +
	ggtitle( "CEBPB" ) +
	theme_bw() +
	theme(
		axis.title = element_text( size=22 ),
		axis.text = element_text( size=20 ),
		plot.title = element_text( size=22, hjust=0.5 )
	)

plot_grid( ctcf.plot, cebpb.plot, nrow=1, labels=c( "A", "B" ) )
```

```{r run_time_combined}
cbPalette = c( "#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7" )

ggplot( run_stats, aes( x = as.numeric( CPU ), y = mean_time, group=Motif, fill=Motif ) ) +
	theme_bw() +
	geom_ribbon( aes( ymin = mean_time - sd_time, ymax = mean_time + sd_time ) ) +
	scale_fill_manual( values=cbPalette ) +
	geom_point( aes( shape=Motif ), size=4 ) +
	geom_line() +
	theme( legend.position = c( 0.75, 0.9 ),
				 legend.background = element_rect( linetype="solid", colour="black" ) ) +
	scale_y_continuous( limits=c(0,600) ) +
	scale_x_continuous( breaks=seq( 1, 10 ) ) +
	xlab( "\nProcessors" ) +
	ylab( "Time (s)\n" ) +
	theme(
		axis.title = element_text( size=22 ),
		axis.text = element_text( size=20 ),
		plot.title = element_text( size=22, hjust=0.5 ),
		legend.title = element_text( size=18 ),
		legend.text = element_text( size=14 )
	)
```

# Test what features matter for time as a linear model

```{r lm}
runtimes <- runtimes %>%
	mutate( motif_size = str_length( Motif ) )

model <- lm( actual_time ~ CPU * motif_size, data=runtimes )

summary( model )

anova( model )
```

# Get overall runtime stats compiled

```{r load_fimo_benchmarks}
file_path = "fimo_benchmark"

fimo_runtimes <- data_frame( filename = dir( file_path, pattern="*.log" ) ) %>%
	mutate( full_path = file.path( file_path, filename ) ) %>%
	mutate( actual_time = map( full_path, read_times, skip_num=0 ) ) %>%
	unnest( . ) %>%
	mutate( tosplit = str_replace( filename, ".log", "" ) ) %>%
	separate( col = tosplit, into = c( "CPU", "Iteration", "Motif" ), sep = "_" )

fimo_run_stats <- fimo_runtimes %>%
	group_by( Motif, CPU ) %>%
	summarize( mean_time = mean( actual_time ), sd_time = sd( actual_time ) )
```

```{r show_output}
as.data.frame( run_stats ) %>%
	mutate( CPU = as.integer( CPU ) ) %>%
	arrange( Motif, CPU )

as.data.frame( fimo_run_stats ) %>%
	mutate( CPU = as.integer( CPU ) ) %>%
	arrange( Motif, CPU )
```

# Determine overlap between FIMO and motif scraper for one sequence

```{r test_overlap}
motif_scraper_uids <- read_csv( file = "motifs/ATTACACAAT.csv", col_names = TRUE, col_types = 'ciiccc' ) %>%
	mutate( uid = case_when(
		Strand == "+" ~ paste( Contig, Start, End, Strand, "ATTACACAAT", sep = "_" ),
		Strand == "-" ~ paste( Contig, End, Start, Strand, "ATTACACAAT", sep = "_" ) ) ) %>%
	pull( uid )

fimo_uids <- read_tsv( "std_fimo/VTKDYRHAAY/fimo.txt", skip = 1, col_names = c( 'motif_id', 'motif_alt_id', 'sequence_name', 'start', 'stop', 'strand', 'score', 'pvalue', 'qvalue', 'seq' ), col_types = 'ccciicdddc' ) %>%
	filter( seq == "ATTACACAAT" ) %>%
	mutate( uid = paste( sequence_name, start, stop, strand, seq, sep = "_" ) ) %>%
	arrange( sequence_name, start, stop, strand ) %>%
	pull( uid )

unique_uid_list <- c( motif_scraper_uids, fimo_uids ) %>%
	unique( . )

upset_df <- data.frame( uid = unique_uid_list ) %>%
	mutate( MotifScraper = case_when(
		uid %in% motif_scraper_uids ~ 1,
		TRUE ~ 0 ) ) %>%
	mutate( FIMO = case_when(
		uid %in% fimo_uids ~ 1,
		TRUE ~ 0 ) )

upset( upset_df, text.scale=c( 3, 3, 3, 2, 3, 3), point.size=5, line.size=2 )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```

